# Generated by Django 2.2.4 on 2019-08-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('name', models.CharField(max_length=128)),
                ('entering', models.IntegerField()),
                ('exiting', models.IntegerField()),
            ],
        ),
    ]
